import random
import string

ADMIN_IDS = [361516746]
DEVELOPER_CHAT_ID = 361516746

# QUIZ_PASSWORD = ''.join(random.choices(string.ascii_lowercase + string.ascii_uppercase + string.digits, k=5))

QUIZ_PASSWORD = 'forwardexam'

# @FORWARDSCHOOLUZ_BOT
VIDEO_1_ID = 'BAACAgIAAxkBAAIGXmBVAqTtAxHsGJ2PFL9X7F3MQVOBAAL5CgAC4bZASh0Bl410sJfNHgQ'
VIDEO_2_ID = 'BAACAgIAAxkBAAIGX2BVAtd31txmxSP0iweIgZ2ncxnEAAJ4CwAC2D15SsqJ_GgHvtr9HgQ'
VIDEO_3_ID = 'BAACAgIAAxkBAAIGYGBVAu7ZhEtUnwoBr3xqqNbHZ2uvAALpDAACFhppSjpuREjURqVlHgQ'

INTENSIVE_6_PHOTO = 'AgACAgIAAxkBAAIW1GBciH33kn5bcPw61qFJ8_N9OpI0AALgsjEbB4fgSmFiswtoIezWiNM1ny4AAwEAAwIAA20AA7IyAgABHgQ'
INTENSIVE_7_PHOTO = 'AgACAgIAAxkBAAIYJWBcmShc9V0rpGKEk1TzUt57I-1rAAILszEbB4fgSjUYXy_a2sKsqzTtly4AAwEAAwIAA20AA6yBBwABHgQ'
GENERAL_ENGLISH_PHOTO = 'AgACAgIAAxkBAAIX_GBclZ78CUIZ52J-JxspDwLYLas8AAIBszEbB4fgSmKQ18lCOUjcDeHKoi4AAwEAAwIAA20AAyRJAAIeBA'
IELTS_PHOTO = 'AgACAgIAAxkBAAIW1GBciH33kn5bcPw61qFJ8_N9OpI0AALgsjEbB4fgSmFiswtoIezWiNM1ny4AAwEAAwIAA20AA7IyAgABHgQ'
# ----------------------------------------------------------

# @FORWARDSCHOOLBOT
# VIDEO_1_ID = 'BAACAgIAAxkBAAILPmCLrNDWGx2HuwKFxPSwoBUUiwmgAAL5CgAC4bZASsWqVCtT90cZHwQ'
# VIDEO_2_ID = 'BAACAgIAAxkBAAILQGCLrN7QLzMkvpBun_6LKyXy-niVAAJ4CwAC2D15ShLr16GUFVlsHwQ'
# VIDEO_3_ID = 'BAACAgIAAxkBAAILQ2CLrPd5WsbAIjd_U_QBz-2cUp-DAALpDAACFhppSi5mh9eaNWgvHwQ'
#
# INTENSIVE_6_PHOTO = 'AgACAgIAAxkBAAILMmCLrHl_DgfYIwHzIg1hZiW8c7rxAAKdtDEbHupYSBrfRX1LnazGG8bSmi4AAwEAAwIAA20AA4fYBQABHwQ'
# INTENSIVE_7_PHOTO = 'AgACAgIAAxkBAAILNGCLrI-Ja3O328OvP_uTcLk3wvgfAALltjEbP5pYSK-aJ-cxNY3at1Cpoi4AAwEAAwIAA20AA5mrAQABHwQ'
# GENERAL_ENGLISH_PHOTO = 'AgACAgIAAxkBAAILNmCLrJ2thqsrdQEO13oAAS2XXnki7gAC5rYxGz-aWEh_9rb-y8UDi_vvzaIuAAMBAAMCAANtAAPFlgEAAR8E'
# IELTS_PHOTO = 'AgACAgIAAxkBAAILOGCLrK4CttqP8is9rPXAvh5iAlfLAAKdtDEbHupYSBrfRX1LnazGG8bSmi4AAwEAAwIAA20AA4fYBQABHwQ'