
questions = {
    '1': '[{}/50] I ____________ from France.',
    '2': '[{}/50] This is my friend. ____________ name is Peter.',
    '3': '[{}/50] Mike is ____________.',
    '4': '[{}/50] My brother is ____________ artist.',
    '5': '[{}/50] ____________ 20 desks in the classroom.',
    '6': '[{}/50] Paul ____________ romantic films.',
    '7': "[{}/50] Sorry, I can't talk. I ____________ now.",
    '8': '[{}/50] She ____________ at school last week.',
    '9': "[{}/50] I ____________ the film last week.",
    '10': "[{}/50] ____________ a piece of cake? No, thank you.",
    '11': "[{}/50] The living room is ____________ than the bedroom.",
    '12': "[{}/50] The car is very old. We're going ____________ a new car soon.",
    '13': "[{}/50] Jane is a vegetarian. She ____________ meat.",
    '14': "[{}/50] There aren't ____________ buses late in the evening.",
    '15': "[{}/50] The car park is ____________ to the restaurant.",
    '16': "[{}/50] Sue ____________ shopping every day.",
    '17': "[{}/50] They ____________ in the park when it started to rain heavily.",
    '18': "[{}/50] ____________ seen fireworks before?",
    '19': "[{}/50] We've been friends ____________ many years.",
    '20': "[{}/50] You ____________ pay for the tickets. They're free.",
    '21': "[{}/50] Jeff was ill last week and he ____________ go out.",
    '22': "[{}/50] These are the photos ____________ I took on holiday.",
    '23': "[{}/50] We'll stay at home if it ____________ this afternoon.",
    '24': "[{}/50] He doesn't smoke now, but he ____________ a lot when he was young.",
    '25': "[{}/50] Mark plays football ____________ anyone else I know.",
    '26': "[{}/50] I promise I ____________ you as soon as I've finished this cleaning.",
    '27': "[{}/50] This town ____________ by lots of tourists during the summer.",
    '28': "[{}/50] He said his friends ____________ to speak to him after they lost the football match.",
    '29': "[{}/50] How about ____________ to the cinema tonight?",
    '30': "[{}/50] Excuse me, can you ____________ me the way to the station, please?",
    '31': "[{}/50] I wasn't interested in the performance very much. ____________.",
    '32': "[{}/50] Take a warm coat, ____________ you might get very cold outside.",
    '33': "[{}/50] ____________ this great book and I can't wait to see how it ends.",
    '34': "[{}/50] What I like more than anything else ____________ at weekends.",
    '35': "[{}/50] She ____________ for her cat for two days when she finally found it in the garage.",
    '36': "[{}/50] We won't catch the plane ____________ we leave home now! Please hurry up!",
    '37': "[{}/50] If I hadn't replied to your email, I ____________ here with you now.",
    '38': "[{}/50] Do you think you ____________ with my mobile phone soon? I need to make a call.",
    '39': "[{}/50] I don't remember mentioning ____________ dinner together tonight.",
    '40': "[{}/50] Was it Captain Cook ____________ New Zealand?",
    '41': "[{}/50] You may not like the cold weather here, but you'll have to ____________. I'm afraid.",
    '42': "[{}/50] It's cold so you should ____________ on a warm jacket.",
    '43': "[{}/50] Paul will look ____________ our dogs while we're on holiday.",
    '44': "[{}/50] She ____________ a lot of her free time reading.",
    '45': "[{}/50] Hello, this is Simon. Could I ____________ to Jane, please?",
    '46': "[{}/50] They're coming to our house ____________ Saturday.",
    '47': "[{}/50] I think it's very easy to ____________ debt these days.",
    '48': "[{}/50] Come on! Quick! Let's get ____________!",
    '49': "[{}/50] I phoned her ____________ I heard the news.",
    '50': "[{}/50] I feel very ____________. I'm going to go to bed!"
}

options = {
    '1': ['is', 'are', 'am', 'be'],
    '2': ['Her', 'Our', 'Yours', 'His'],
    '3': ["my sister's friend", 'friend my sister', 'friend from my sister', "my sister friend's"],
    '4': ['the', 'an', 'a', '3/4'],
    '5': ['This is', 'There is', 'They are', 'There are'],
    '6': ['likes not', "don't like", "doesn't like", "isn't likes"],
    '7': ["driving", "'m driving", "drives", "drive"],
    '8': ["didn't be", "weren't", "wasn't", "isn't"],
    '9': ["like", "likes", "liking", "liked"],
    '10': ["Do you like", "Would you like", "Want you", "Are you like"],
    '11': ["more big", "more bigger", "biggest", "bigger"],
    '12': ["to buy", "buying", "to will buy", "buy"],
    '13': ["sometimes eats", "never eats", "often eats", "usually eats"],
    '14': ["some", "any", "no", "a"],
    '15': ["next", "opposite", "behind", "in front"],
    '16': ["is going", "go", "going", "goes"],
    '17': ["walked", "were walking", "were walk", "are walking"],
    '18': ["Do you ever", "Are you ever", "Have you ever", "Do you ever"],
    '19': ["since", "from", "during", "for"],
    '20': ["have to", "don't have", "don't need to", "doesn't have to"],
    '21': ["needn't", "can't", "mustn't", "couldn't"],
    '22': ["which", "who", "what", "where"],
    '23': ["raining", "rains", "will rain", "rain"],
    '24': ["has smoked", "smokes", "used to smoke", "was smoked"],
    '25': ["more good than", "as better as", "best than", "better than"],
    '26': ["will help", "am helping", "going to help", "have helped"],
    '27': ["visits", "visited", "is visiting", "is visited"],
    '28': ["not want", "weren't", "didn't want", "aren't wanting"],
    '29': ["going", "go", "to go", "for going"],
    '30': ["give", "take", "tell", "say"],
    '31': ["I didn't, too.", "Neither was I.", "Nor I did.", "So I wasn't"],
    '32': ["otherwise", "in case", "so that", "in order to"],
    '33': ["I don't read", "I've read", "I've been reading", "I read"],
    '34': ["playing off", "to play golf", "is playing golf", "is play golf"],
    '35': ["looked", "had been looked", "had been looking", "were looking"],
    '36': ["if", "providing that", "except", "unless"],
    '37': ["can't be", "wouldn't be", "won't be", "haven't been"],
    '38': ["finish", "are finishing", "will have finished", "are finished"],
    '39': ["go for", "you going to", "to go for", "going for"],
    '40': ["who discovered", "discovered", "that discover", "who was discovering"],
    '41': ["tell it off", "sort itself out", "put up with it", "put it off"],
    '42': ["put", "wear", "dress", "take"],
    '43': ["at", "for", "into", "after"],
    '44': ["does", "spends", "has", "makes"],
    '45': ["say", "tell", "call", "speak"],
    '46': ["in", "at", "on", "with"],
    '47': ["go into", "become", "go down to", "get into"],
    '48': ["highlight", "cracking", "massive", "with immediate effect"],
    '49': ["minute", "during", "by the time", "the moment"],
    '50': ["nap", "asleep", "sleepy", "sleeper"]
}

# A - 0
# B - 1
# C - 2
# D - 3

answers = {
    '1': '2',
    '2': '3',
    '3': '0',
    '4': '1',
    '5': '3',
    '6': '2',
    '7': '1',
    '8': '2',
    '9': '3',
    '10': '1',
    '11': '3',
    '12': '0',
    '13': '1',
    '14': '1',
    '15': '0',
    '16': '3',
    '17': '1',
    '18': '2',
    '19': '3',
    '20': '2',
    '21': '3',
    '22': '0',
    '23': '1',
    '24': '2',
    '25': '3',
    '26': '0',
    '27': '3',
    '28': '2',
    '29': '0',
    '30': '2',
    '31': '1',
    '32': '0',
    '33': '2',
    '34': '2',
    '35': '2',
    '36': '3',
    '37': '1',
    '38': '2',
    '39': '3',
    '40': '0',
    '41': '2',
    '42': '0',
    '43': '3',
    '44': '1',
    '45': '3',
    '46': '2',
    '47': '3',
    '48': '1',
    '49': '3',
    '50': '2'
}
